<a href="https://colab.research.google.com/github/yyinsomnia/build-cngpt/blob/main/gpt_mao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 环境和依赖



In [ ]:
!wget https://raw.githubusercontent.com/yyinsomnia/openai-ex/main/input.txt

--2024-07-13 09:01:49--  https://raw.githubusercontent.com/yyinsomnia/openai-ex/main/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42761 (42K) [text/plain]
Saving to: ‘input.txt’

input.txt           100%[===================>]  41.76K  --.-KB/s    in 0.01s   

2024-07-13 09:01:49 (3.49 MB/s) - ‘input.txt’ saved [42761/42761]



# 传统的语言模型bigram

In [ ]:
with open('input.txt') as f:
    text = f.read()

In [ ]:
print('length of the mao-poetic in characters is :', len(text))

length of the mao-poetic in characters is : 16498


In [ ]:
print(text[:1000])

# 西江月·秋收起义

军叫工农革命，

旗号镰刀斧头。

匡庐一带不停留，

要向潇湘直进。

地主重重压迫，

农民个个同仇。

秋收时节暮云愁，

霹雳一声暴动。




# 菩萨蛮·黄鹤楼

茫茫九派流中国，

沉沉一线穿南北。

烟雨莽苍苍，

龟蛇锁大江。

黄鹤知何去？

剩有游人处。

把酒酹滔滔，

心潮逐浪高！




# 七律·和柳亚子先生

饮茶粤海未能忘，索句渝州叶正黄。

三十一年还旧国，落花时节读华章。

牢骚太盛防肠断，风物长宜放眼量。

莫道昆明池水浅，观鱼胜过富春江。




# 七律·冬云

雪压冬云白絮飞，万花纷谢一时稀。

高天滚滚寒流急，大地微微暖气吹。

独有英雄驱虎豹，更无豪杰怕熊罴。

梅花欢喜漫天雪，冻死苍蝇未足奇。




# 七律·到韶山

别梦依稀咒逝川，故园三十二年前。

红旗卷起农奴戟，黑手高悬霸主鞭。

为有牺牲多壮志，敢教日月换新天。

喜看稻菽千重浪，遍地英雄下夕烟。




# 四言诗·祭母文

呜呼吾母，遽然而死。寿五十三，生有七子。

七子余三，即东民覃。其他不育，二女二男。

育吾兄弟，艰辛备历。摧折作磨，因此遘疾。

中间万万，皆伤心史。不忍卒书，待徐温吐。

今则欲言，只有两端：一则盛德，一则恨偏。

吾母高风，首推博爱。远近亲疏，一皆覆载。

恺恻慈祥，感动庶汇。爱力所及，原本真诚。

不作诳言，不存欺心。整饬成性，一丝不诡。

手泽所经，皆有条理。头脑精密，擘理分情。

事无遗算，物无遁形。洁净之风，传遍戚里。

不染一尘，身心表里。五德荦荦，乃其大端。

合其人格，如在上焉。恨偏所在，三纲之末。

有志未伸，有求不获。精神痛苦，以此为卓。

天乎人欤，倾地一角。次则儿辈，育之成行。

如果未熟，介在青黄。病时揽手，酸心结肠。

但呼儿辈，各务为良。又次所怀，好亲至爱。

或属素恩，或多劳瘁。大小亲疏，均待报赍。

总兹所述，盛德所辉。必秉悃忱，则效不违。

致于所恨，必补遗缺。念兹在兹，此心不越。

养育深恩，春辉朝霭。报之何时，精禽大海。

呜呼吾母，母终未死。躯壳虽隳，灵则万古。

有生一日，皆报恩时。有生一日，皆伴亲时。

今也言长，时则苦短。惟挈大端，置其粗浅。

此时家奠，尽此一觞。后有言陈，与日俱长。




# 清平乐 蒋桂战争

风云突变，

军阀重开战。

洒向人

In [ ]:
chars = sorted(list(set(text)))
vocab_size = len(chars)

In [ ]:
print(''.join(chars))
print(vocab_size)


 #*AB·“”…　、。《》一丁七万丈三上下不与且世业丛东丝两严丧个中丰临丸丹为主丽举乃久么义之乌乎乐乔乘九也习乡书买乱乾了争事二于云五井亚些亟亡交亥亦产亩京亭亲人亿什仇今介仍从仑仓他仗付仙仞代令以仰仲任份仿伍伏休众会伟传伤伦伫伴伸似但位低住佐何佗余作你佳例供依侠侣侮侯侵便俊俏俘保信修俯俱倒倚倜借倦倭债倾假偏偕做停健偶偷偿傅傍傥催傲僧儿兀元兄充兆先光免兔党入全八公六兮兰共关兴兵其兹养兼冀内冈冉再冒冕写军农冠冢冬冯冰冲决况冷冻净凄准凉凋凌减几凡凤凭凯凰凶出击刀分切划列刘则刚初判利别到制刺前剑剧剩副割剿力劝办功加务劣动努劫劲劳势勇勤勾勿匈匕化北匝匡匪区医十千卅升午半华卑卒卓单卖南博卜占卢卧卫印危即却卵卷卿厂历厉压厚原去县参又及友双反发取受变叛叟叠口古句只叫叭可台史叶号司叹吃各合吉吊同名后吏吐向吓君吟否含听启吴吸吹吻吼吾呀呈告员呜周味呼命和咎咏咒咬咽哀响哎哥哨哪哭唇唐唤唯唱商啥啸啼善喇喊喋喑喜喝嗟嗡嘉嘶嚣囊四回因团园困围固国图囿圃圆土圣在地场均坏坐坑坚坠坤垂垄垒垓埃埋城域培基堂堆堑堕堤堪塔塘塞境墓墙增墟墨墩壁壑壤士壮声壳处备复夏夕外多夜大天太夫央失头夷夸夺奇奈奉奋奏奔奚奠女奴奸她好如妄妆妇妍妖妙妨妻始姐委姿威娄娆娇娓娘娥娴婢媚嫦嫩子孔字存孙季孤学孩孽宁宇守安宋完宏宗官宙定宜宝实宠客宣宫害宴宵家容宽宾宿寂寄密寇富寐寒寞寥寨寰寸对寺寻导寿封射将尊小少尔尘尚尤尧就尸尺尼尽屁层居屈屋展属屠履屦山岁岂岖岛岩岭岳岷岸岿峙峡峥峦峨峰峻崇崎崖崩嵘嶂嶷川州巡工巧巨巫己已巾市布帆师帐帜帝带席帷常幕干平年并幸幽广庄庆床庐应底庙府废度庭庶康廊廓廖延建开异弃弄弓引弟张弥弦弯弱弹强归当形彩彪彭影彻彼往征待徊律徐徒得徘御微德心必忆忍志忘忙忠忡忧快忱念忽怀态怅怎怒怕怜思急性怨怪总恋恍恐恙恨恩息恰恶恺恻悃悚患悬悲情惆惊惜惟惨惯想愁意愚感愤愿慈慌慧慨慷懈懿戈戎戏成我或战戚戟截戴户房所扇手才打托执扫扬扭扶批承技把抒抓投抗折抛报披抱抵抹抽拂拄担拍拒拖拘招拜拥拼拾持挂指挈按挖挟挡挥振挺挽捆捉捐损换捣捧捷掌排掣接推掩插揖握揽搅搏携摄摇摔摧摩撼擘擦攀收改攻放政故效敌救教敝敢散敦数整文斑斗料斜斥斧断斯新斶方施旁旅旋旌族旗无日旦旧旨早旭时旺昂昆昌明昏易昔星映春昨昭是晋晏晓晖晚晨普景晴晶智暂暑暖暗暮暴曙曦曰曲更曹曾最月有朋服朔朗望朝期木未末本朱朵机朽杀杂权李材村杖杜条来杨杭杯杰杷松板极枇枉析枕林果枝枪枯架柏染查柱柳标树株

In [ ]:
stoi = {char:idx for idx, char in enumerate(chars)}
itos = {idx: char for idx, char in enumerate(chars)}

In [ ]:
print(stoi['北'])
print(itos[273])

273
北


In [ ]:
encode = lambda s: [stoi[c] for c in s]
decode = lambda ids: ''.join([itos[i] for i in ids])

In [ ]:
print(encode('北国风光'))
print(decode([273, 415, 2025, 176]))

[273, 415, 2025, 176]
北国风光


In [ ]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([16498]) torch.int64
tensor([   2,    1, 1678, 1082,  947,    6, 1385,  865, 1772,   47,    0,    0,
         203,  330,  628,  204, 2001,  371, 2102,    0,    0,  899,  336, 1930,
         231,  887,  479,   12,    0,    0,  275,  657,   15,  642,   23,  158,
        1305, 2102,    0,    0, 1679,  349, 1193, 1170, 1335, 1828,   12,    0,
           0,  423,   41, 1894, 1894,  308, 1834, 2102,    0,    0,  204, 1067,
          34,   34,  344,   85,   12,    0,    0, 1385,  865,  907, 1571,  937,
          67,  758, 2102,    0,    0, 1995, 1981,   15,  463,  938,  260,   12,
           0,    0,    0,    0,    0,    2,    1, 1609, 1616, 1649,    6, 2089,
        2084, 1027,    0,    0, 1589, 1589,   54, 1125, 1126,   35,  415, 2102,
           0,    0, 1091, 1091,   15, 1463, 1408,  291,  273,   12,    0,    0,
        1220, 1979, 1605, 1576, 1576, 2102,    0,    0, 2098, 1646, 1919,  473,
        1082,   12,    0,    0, 2089, 2084, 1354,  123,  311, 2105,    0,    0,
        

In [ ]:
n = int(0.9 * len(data))
train_data = data[:n]
valid_data = data[n:]

In [ ]:
block_size = 8
train_data[:block_size+1]

tensor([   2,    1, 1678, 1082,  947,    6, 1385,  865, 1772])

In [ ]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for i in range(block_size):
    context = x[:i+1]
    target = y[i]
    print(f"when context is {context}, target is {target}")

when context is tensor([2]), target is 1
when context is tensor([2, 1]), target is 1678
when context is tensor([   2,    1, 1678]), target is 1082
when context is tensor([   2,    1, 1678, 1082]), target is 947
when context is tensor([   2,    1, 1678, 1082,  947]), target is 6
when context is tensor([   2,    1, 1678, 1082,  947,    6]), target is 1385
when context is tensor([   2,    1, 1678, 1082,  947,    6, 1385]), target is 865
when context is tensor([   2,    1, 1678, 1082,  947,    6, 1385,  865]), target is 1772


In [ ]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else valid_data
    ix = torch.randint(len(data) - block_size, (batch_size,))

    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1: i+block_size+1] for i in ix])
    return x, y

# print(get_batch('train'))
xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

inputs:
torch.Size([4, 8])
tensor([[  17, 1456, 1393,  600,  711, 2102,    0,    0],
        [2102,    0,    0, 1678, 2025, 1192,  303,  527],
        [ 111, 1858,  778, 1893,   12,    0,    0,   23],
        [2042,    6,  866, 1538,   52,  956,   13,  552]])
targets:
torch.Size([4, 8])
tensor([[1456, 1393,  600,  711, 2102,    0,    0,  710],
        [   0,    0, 1678, 2025, 1192,  303,  527,  438],
        [1858,  778, 1893,   12,    0,    0,   23,  993],
        [   6,  866, 1538,   52,  956,   13,  552,   58]])


In [ ]:
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f'when context is {context}, target is {target}')

when context is tensor([17]), target is 1456
when context is tensor([  17, 1456]), target is 1393
when context is tensor([  17, 1456, 1393]), target is 600
when context is tensor([  17, 1456, 1393,  600]), target is 711
when context is tensor([  17, 1456, 1393,  600,  711]), target is 2102
when context is tensor([  17, 1456, 1393,  600,  711, 2102]), target is 0
when context is tensor([  17, 1456, 1393,  600,  711, 2102,    0]), target is 0
when context is tensor([  17, 1456, 1393,  600,  711, 2102,    0,    0]), target is 710
when context is tensor([2102]), target is 0
when context is tensor([2102,    0]), target is 0
when context is tensor([2102,    0,    0]), target is 1678
when context is tensor([2102,    0,    0, 1678]), target is 2025
when context is tensor([2102,    0,    0, 1678, 2025]), target is 1192
when context is tensor([2102,    0,    0, 1678, 2025, 1192]), target is 303
when context is tensor([2102,    0,    0, 1678, 2025, 1192,  303]), target is 527
when context is tens

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # 这里是有讲究的，这个embedding就是通过当前词预测下一个词，这是bigram吗？怎么感觉是unigram
        # 没问题，就是bigram。uniqgram就是每个词的出现只与它自己有关，bigram是每个词的出现与它的前一个有关
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)

        return idx

In [ ]:
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 2106])
tensor(7.9996, grad_fn=<NllLossBackward0>)

滂东分赞项批孙单蹉泄摔壮聋答方椰勿诉冬苦簧身鲜印育指景素亥莱望租古第奉谣锄卢岖装逝况守辞蒸转解诳误呼料恍误久卷妙辛昌登怕覆执渔因宾问桑忡日见色这镜壮呀鹤雄携入卒酒儿依园妻议必今皆土裹应房薄民跹荣鲁瀛明


In [ ]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [ ]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# 基本到2.2 就下不去了
print(loss.item())


3.9428210258483887


In [ ]:
torch.zeros(1, 1, dtype=torch.long)

tensor([[0]])

In [ ]:
gen_idx = torch.tensor([encode('北国风光')], dtype=torch.long)
gen_idx

tensor([[ 273,  415, 2025,  176]])

In [ ]:
print(decode(m.generate(idx = gen_idx, max_new_tokens=500)[0].tolist()))

北国风光。

致尽红旗过薄浣楼狼除阁检效赍村证张传蜮妍结肇脚泪颁逐寰这遏杨导故辞节两疾贱艨巡击楫矛侯节偏瑜间颅仍停肯讶旋风追热县喋语·改康荣朽添亿瞻寄散蛇郸虏蚂救会惟　字娓罢粗固倒军纵入诗句迤铐猜严木镇炬有两囿枇斶驻羊旭艰屠喇间，如虎堤氤蛙牛南陷岳冯绩毕恋尔可该俯赃表寰寿酸冢溟毅肉虏涸尔钢赔鄂偿插荣意多文咏汨蕡银闲。

求怜去？


旧弄叛贫樯借颇工农民满橘娓桃仇。
横判荆萋圆报袍颇哀赔奠豪，
一生乃忘蜡置讨置草麦银膊嘉渺帆幸凤饿领谒兆贼。

六洲赔虏卅买欧塞按奉恺敦鸿尚主红蹇炊欧母终兄夷豚兔怅煎欤分裂足题掩多抓倦托毅卿即卑宁观摔漫春夏兮滚汀直料升伟业见柱通府妻遇窗虎菩磨，把寞治艟洛萧生涯顿嘉眼沦刚





吾呀杯鬓寻位坚。
# 七律·改陈眺孤阵辉影相竞徐章西直穿丹亩票际衣被豹捧凯务夕铃湘鼎泽信绅通取孽海翻奉尤迫。

到演妙雹恋岖列友面点涎帐富饿懿陇踪起眉参莽减刚贰遗帷橘铭城东汉黍床棒述鲜隆猜似械寨椒溯偷盾民宗卑天高富秽梁感鹰残骸鸡羽陷联盾猴现载炊氤荔穷寇冕判等尼翘欢各魂祖蓝宽把薄亩载嵘郊稍踊铺笞列撼硬船灯票廖懿栽球倒，
开颜斶笼母棹映柱开争解逐紫鞍装傍战懈名青山红霞两况赖赫其遏慈饱嶂崎踯指


# attention的数学技巧

In [ ]:
torch.manual_seed(42)
# 下三角矩阵就能做到和左边的词元attention
a = torch.tril(torch.ones(3, 3))
# 但是这里我们要模拟的不是mask，而是一个K * Q得到的attention权重矩阵，还得归一化
a = a / torch.sum(a, 1, keepdim=True)

b = torch.randint(0,10,(3,2)).float()

c = a @ b
print('a=')
print(a)
print('---')
print('b=')
print(b)
print('c=')
print('---')
print(c)

# c look as the column combination of a
# 2.  0. 0  2
# 1.  3. 0. 4
# 2/3 2  2. 4.6666

# 但是这里应该看成 row combination of b
# 1.0 * [2., 7.] + 0.0 * [6., 4.] + 0.0 * [6., 5.] 这就是第1个token的BOW表示
# 0.5 * [2., 7.] + 0.5 * [6., 4.] + 0.0 * [6., 5.] 这就是第2个token的BOW表示
# 0.3 * [2., 7.] + 0.3 * [6., 4.] + 0.3 * [6., 5.] 这就是第3个token的BOW表示


a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
---
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
c=
---
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
torch.manual_seed(1337)
B, T, C = 4, 8, 2
x = torch.randn(B, T, C)
print(x)

tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643],
         [ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]],

        [[ 1.3488, -0.1396],
         [ 0.2858,  0.9651],
         [-2.0371,  0.4931],
         [ 1.4870,  0.5910],
         [ 0.1260, -1.5627],
         [-1.1601, -0.3348],
         [ 0.4478, -0.8016],
         [ 1.5236,  2.5086]],

        [[-0.6631, -0.2513],
         [ 1.0101,  0.1215],
         [ 0.1584,  1.1340],
         [-1.1539, -0.2984],
         [-0.5075, -0.9239],
         [ 0.5467, -1.4948],
         [-1.2057,  0.5718],
         [-0.5974, -0.6937]],

        [[ 1.6455, -0.8030],
         [ 1.3514, -0.2759],
         [-1.5108,  2.1048],
         [ 2.7630, -1.7465],
         [ 1.4516, -1.5103],
         [ 0.8212, -0.2115],
         [ 0.7789,  1.5333],
         [ 1.6097, -0.4032]]])


In [ ]:
# 先用朴素BOW来表达？
# x[b, t] = mean_{i <= t} x[b, i]

xbow = torch.zeros(B, T, C)
for b in range(B):
    for t in range(T):
        x_expression = torch.mean(x[b, :t+1], 0)
        xbow[b, t] = x_expression

print(xbow)

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])


In [ ]:
# 再用上面那个tril的矩阵乘法来表示

wei = torch.tril(torch.ones(T, T))
print('wei_tril:')
print(wei)


# 这里keepdim=True shape是(8, 1)所以除法就是每行除以对应的那一行的1个sum出来的数
# keepdim=False, shape是(8, ), 那就是每一行从左到右每个元素都找到对应的去除
wei_sum = wei.sum(1, keepdim=True)

print('wei_sum:')
print(wei_sum)
wei = wei / wei_sum


print('wei:')
print(wei)

xbow2 = wei @ x

# 发现太小的值，这里[1,5,1] 是 0.0020，会导致allclose判断为False，
# 这个问题很有意思，我记得21年跑这个代码没有这个问题，现在出现了。我也运行了一下Andrej的原始notebook也是Fasle
# 说明大概率是python和torch的版本升级导致的，可能是seed rand的数字不一样了
print('xbow2:')
print(xbow2[1][5][1])
print(xbow2[1][5][1] - xbow[1][5][1])
torch.allclose(xbow[1][5][1], xbow2[1][5][1])

wei_tril:
tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
wei_sum:
tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])
wei:
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        

False

In [ ]:
# 用softmax
wei = torch.tril(torch.ones(T, T))
wei = torch.where(wei == 0.0, float('-inf'), wei)

"""
在PyTorch中，`F.softmax` 函数用于沿着指定的维度对输入张量进行softmax操作。对于张量 `wei`，其形状为 `(T, T)`，让我们分析一下 `F.softmax(wei, 1)` 和 `F.softmax(wei, -1)` 的含义：

1. **`F.softmax(wei, 1)`**:
   - 这里的 `1` 表示在第1个维度（即列方向）上进行softmax操作。对于每一行，`F.softmax` 会计算该行内的softmax值。

2. **`F.softmax(wei, -1)`**:
   - 这里的 `-1` 表示在最后一个维度上进行softmax操作。对于二维张量 `(T, T)` 来说，最后一个维度也是列方向（即维度1）。因此，`F.softmax(wei, -1)` 实际上与 `F.softmax(wei, 1)` 是等价的。

总结来说，`F.softmax(wei, 1)` 和 `F.softmax(wei, -1)` 在形状为 `(T, T)` 的张量上执行时，是相同的操作，因为它们都在列方向上计算softmax。
"""
wei = F.softmax(wei, 1)
print('wei:')
print(wei)

xbow3 = wei @ x

# xbow2和xbow3是一样的
# 因为xbow2和xbow3都是先除再加，xbow的mean是先加再除
torch.allclose(xbow2, xbow3)

wei:
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])


True

In [ ]:
# 终于来了！自注意力self-attention
torch.manual_seed(1337)

B, T, C = 2, 16, 8

x = torch.randn(B, T, C)

header_size = 4

key = nn.Linear(C, header_size)
query = nn.Linear(C, header_size)
value = nn.Linear(C, header_size)

# k.shape (B, T, head_size)
k = key(x)
q = query(x)
v = value(x)

# wei.shape 应该是(B, T, T)
wei = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(wei == 0.0, float('-inf')) - 1
# 使用 unsqueeze 在第0维度增加一个维度，然后使用 repeat 复制 B 份
wei = wei.unsqueeze(0).repeat(B, 1, 1)
wei += q @ k.transpose(1, 2) # 这里之前写成了v,写错了！！！！！！ q应该和k来算wei

wei = F.softmax(wei, 2)

# x_attented.shape (B, T, head_size)
x_attented = wei @ v

x_attented.shape

torch.Size([2, 16, 4])